### ISSUE TITLE
how to build and run mind front code

### ISSUE THREAD

**Issue by MrYogi** [Minds/front#1]
i am unable to find any core files, how to build and run mind front code

**Comment by markharding** [comment]
Run:

npm install
gulp build

I'd advise against running this repo at present.

**Comment by MrYogi** [comment]
Minds repo missing:
https://github.com/minds/minds

**Comment by markharding** [comment]
This will be released in the future when it is stable

**Comment by MrYogi** [comment]
thanks for reply, so there is no way to run Minds web app and mobile currently?

**Comment by ottman** [comment]
It's coming! ;)

**Comment by Velody** [comment]
I'm still waiting and waiting :cry: :laughing:
