### ISSUE TITLE
(bug): System.import('bootstrap') fails

### ISSUE THREAD

**Issue by Andersama** [Minds/front#21]
Tried to start up a vagrant instance of minds, properly redirected the ip w/ the hosts file and checked out the result, nothing but a spinning wheel of death~

Checked the console log error and found this:

```
Uncaught ReferenceError: System is not defined at (index):110
```

```javascript
System.import('bootstrap').catch(function(){console.error(e,'Report this error at https://github.com/minds/front'});
```

So I decided to report the error despite it not being caught...because system is undefined.

I would hunt down for the System object hidden somewhere in javascript, but I imagine someone has a rough idea of how to fix it. I don't know how important the system variable is, but since it just shows up as a one liner, I'd suggest checking if it's defined before trying to run any of its methods.

```javascript
if(typeof System !== 'undefined'){
System.import('bootstrap').catch(function(){console.error(e,'Report this error at https://github.com/minds/front'});
} else {
console.log('System Undefined! Report this to https://github.com/minds/front');
}
```

Source of the problem:
https://github.com/Minds/front/blob/4f758c0d680bf2890882abd9d14c3dbec23b4242/app/index.php

```php
    <% if (ENV === 'dev') { %>
    <script>
      System.import('<%= BOOTSTRAP_MODULE %>')
        .catch(function(){console.error(e,'Report this error at https://github.com/minds/front')});
    </script>
    <% } %>
```

Not exactly going to dig through code, but as of the most recent commit: https://github.com/Minds/front/commit/e51113f11b0f7560a889882d3a2e5031172a799f

(spinning wheel of death continues, the error above doesn't stop any important javascript execution, seems as if I'm missing some incredibly important things to get this to work*)

**Comment by edgebal** [comment]
Hi @Andersama,

You might have done it, but just in case: Did you build the frontend part?

On `front` folder:
```bash
$ npm install
$ gulp build
$ gulp build.index
```

**Comment by Andersama** [comment]
Developing on windows* so there's a bit of bouncing back and forth because gulp isn't installed as part of minds, but this is what I just ran:
```bash
vagrant up
vagrant ssh
$ cd /var/www/Minds/front
$ npm install
$ exit
cd /front 
gulp build
gulp build.index
```
and the spinning wheel of death is still there, same error, no difference has been made.

**Comment by edgebal** [comment]
Can you confirm `app.js` (~3MB) and `shims.js` (~500KB) exist on `front/public/js` and that they are included in the `<script>` tags on the compiled `index.php` that's on `front/public`? Thanks!

**Comment by Andersama** [comment]
Neither app.js nor shims.js are included in any script tags, and there isn't a front/public/js folder* I imagine they're supposed to have been added there?

**Comment by edgebal** [comment]
That's correct. Can you copy and paste both gulp commands output onto a [GitHub Gist](https://gist.github.com) and paste its link here?

**Comment by Andersama** [comment]
Here's the output of each command: https://gist.github.com/Andersama/e2555dc6b3a56dcfe7e722658385dee1

**Comment by edgebal** [comment]
It seems that you've found a bug with Windows build process! Thanks! The finalization callback wasn't executing because the template plugin was being skipped at the end of the `.map()`.

We're going to ship the fix in the next release, in the meantime you can download a [patch here]( https://gist.github.com/edgebal/0ccb5c637aa5026bfaf5977351c58d2a). Just replace `front/tools/tasks/build.plugins.ts`. Let us know how it went!

PS: You might want to run `npm rebuild node-sass` within cmd/Powershell before. I saw that you ran `npm install` inside the Vagrant machine, if you try to compile on Windows you'll get an `Missing binding` error.

**Comment by Andersama** [comment]
Getting an error from the sass plugin:
```
Error in plugin 'sass'
Message:
    app\stylesheets\components\mature.scss
Error: Undefined variable: "$minds-padding".
        on line 128 of app/stylesheets/components/mature.scss
>>     top: $minds-padding;
   ---------^

app\src\services\api\upload.ts(44,16): error TS2339: Property 'status' does not exist on type 'XMLHttpRequestEventTarget'.
app\src\services\api\upload.ts(45,30): error TS2339: Property 'response' does not exist on type 'XMLHttpRequestEventTarget'.
app\src\services\api\upload.ts(47,18): error TS2339: Property 'response' does not exist on type 'XMLHttpRequestEventTarget'.
```

Is this what you were worrying about?

**Comment by edgebal** [comment]
Those aren't fatal errors. The compilation should be succeeded anyways.

**Comment by Andersama** [comment]
Et voila, a working build*

~merci~

**Comment by Andersama** [comment]
Ok, immediate issue upon signing in, the modal to select categories that I'm supposed to be interested in is empty* hitting continue doesn't appear to do anything.

**Comment by Andersama** [comment]
Just running through some things I'm noticing that if I try to upload a video/audio the post button gets disabled. I was going to test the weird auto-play behavior, but it seems I'll have to figure out that odd bit first*
