### ISSUE TITLE
Concatenate long message titles in notifications

### ISSUE THREAD

**Issue by sevvie** [Minds/front#23]
Currently, when one receives a notification, they will receive with it the ENTIRE message, with carriage returns removed, as the title of the post. I took a screenshot as an example. This makes it very difficult to sift through notifications quickly, but looks like something I might be able to write a PR for rather easily... but I would like to know what everyone else thinks as I'm just an OSS hacker on the outside.

![minds-long-titles](https://cloud.githubusercontent.com/assets/1657272/23925898/be8a1e74-08e7-11e7-8df6-95bce9c1a5e8.png)

**Comment by bobdabiulder** [comment]
Is this fixed?  If not, where is it in the code?  I will fix it.

**Comment by markharding** [comment]
Checkout https://github.com/Minds/front/blob/master/app/src/controllers/cards/activity/activity.html#L36

**Comment by markharding** [comment]
@bobdabiulder  are you wanting to work on this?

**Comment by bobdabiulder** [comment]
Yes Mark, but it seems very involved to join now.  The classes alone are tough to hunt down.

**Comment by umbrella-roman-kudlay** [comment]
Hi, guys.
I'd like to make PR for this issue.
I see title displayed "as is", so, I think what title may be limited by N chars (eg. 40 chars, length may be stored in config) and will be added "..." for cutted titles

**Comment by bobdabiulder** [comment]
I like that idea.  I'm too busy to look through all the code and style sheets to see what changes may be necessary to fix this, however.  Should be easy enough.  Abstractly, this is what should be done:

- Get the characters between indices 0 and 39
- add "..." to the end
- print/echo the result

**Comment by ottman** [comment]
This is fixed. Would love your feedback on the new app as it's been a while since this issue was created!
