### ISSUE TITLE
Totally non-obvious what /newsfeed mdl-switch does

### ISSUE THREAD

**Issue by djbclark** [Minds/front#24]
There is a left-right toggle switch UI element that seems to correspond to:
`<span class="mdl-switch__ripple-container mdl-js-ripple-effect mdl-ripple--center"><span class="mdl-ripple"></span></span>`
Switching it doesn't seem to do anything, and it has no mouseover tooltip text.

It's kinda infuriating.

**Comment by djbclark** [comment]
Maybe this should be merged with https://github.com/Minds/minds/issues/30

**Comment by markharding** [comment]
This is for the boost rotator.

**Comment by ottman** [comment]
It's true it is very unclear. What do you recommend
