### ISSUE TITLE
Remove third party web dependencies (probably should migrate from /minds)

### ISSUE THREAD

**Issue by electricessence** [Minds/front#25]
https://github.com/Minds/minds/issues/27

Aside from this, I'd like to make a couple compliments:
1) I like what you are doing, and I hope that if you can clean up the 3rd party dependencies that this could be the social platform for the future.
2) Seems like most of your code on /front is TypeScript.  Kudos.

**Comment by bobdabiulder** [comment]
What is typescript

**Comment by markharding** [comment]
closing as duplicate of Minds/minds#27
