### ISSUE TITLE
Installation process is Fatal

### ISSUE THREAD

**Issue by ubuntume** [Minds/front#29]
I've ran the prep script on a dedicated machine it was full of errors and request to make a report. Not so sure whatsup

**Comment by ottman** [comment]
Did you utilize https://GitHub.com/minds/minds/wiki?

**Comment by ubuntume** [comment]
Yes sir. It fails with virtualbox on my windows machine. I was also looking
to test it on one of my dedicated machines as a clean install, but I'm
reluctant because the only issue with virtualbox seemed to be networking.

Any advice about a comparison between a virtualbox and a dedicated machine.
Is there a way around vagrant and virtual environments?

**Comment by markharding** [comment]
A couple of the internal team are using this on windows so they might be able to help.

**Comment by edgebal** [comment]
Hey there! Are you using vagrant? Or you're setting up manually?

If you're **NOT** using vagrant, ensure you have 2 network interfaces:
1) a NAT interface to be able to connect to the internet
2) a host-only interface to have host-machine real connectivity. Ensure you set up the host-only interface in VirtualBox's preference first.

If you're using vagrant: Can you attach screenshots (or a pastebin link) with the console output?

Thanks!

**Comment by ubuntume** [comment]
I'm actually trying to accomplish both. I definitely will be using vagrant
for the virtualbox only to see how it's working, but on the dedicated
machine I would much rather prefer manual and stick it straight on.

On Fri, Jun 23, 2017 at 8:16 AM, Emiliano Balbuena <notifications@github.com

**Comment by markharding** [comment]
It's best to get started with the vagrant box, especially for development. 

As long as you have an ubuntu machine, then running https://github.com/Minds/minds/blob/master/bin/bootstrap-ubuntu.sh should also set it up on bare metal. I would not recommend using any other distribution than Ubuntu though.

**Comment by ubuntume** [comment]
Definitely sticking to mirror what you guys have already accomplished.

**Comment by ubuntume** [comment]
So it's up in a virtual machine. I had a networking issue. Now, trying to
run this code from it's own domain name on a dedicated machine seems more
difficult. Any docs to accomplish this?

**Comment by markharding** [comment]
https://www.minds.org/docs/ should help. I wouldn't advise trying to run this on a production environment, especially without having Cassandra setup on at least 3 nodes.

**Comment by ubuntume** [comment]
That's the thing. I have a farm and I'm interested in understanding how
this actually works in a real life example. I have access to as many nudes
or ips as needed.

**Comment by markharding** [comment]
It will work, but you should be aware of the risks before you start, and it will likely be a full time job maintaining the system. 

We should probably open a new ticket or move of the the [Dev Group](https://www.minds.com/groups/profile/365903183068794880/activity). I'm interested in hearing more about your hardware etc and how much load you are expecting.

**Comment by markharding** [comment]
Please open if you're still having issues!
