### ISSUE TITLE
Editing a Remind-ed media will edit the text of the media not of the Remind

### ISSUE THREAD

**Issue by xftroxgpx** [Minds/front#36]
This is the Remind of a media:
![screenshot_2017-10-15_05-08-04](https://user-images.githubusercontent.com/26243389/31581250-f6b41016-b166-11e7-9248-ace3bc401fe8.png)

When I click Edit (as seen above), I am only able to edit the text that exists on the media, not the one of the post(when I entered during Remind)
![screenshot_2017-10-15_05-08-23](https://user-images.githubusercontent.com/26243389/31581254-125b5e78-b167-11e7-8d13-a33ba754fab0.png)

This is the media which got Reminded
![screenshot_2017-10-15_05-10-41](https://user-images.githubusercontent.com/26243389/31581259-3df7675c-b167-11e7-8bd9-8ab5fb404e64.png)

**Comment by markharding** [comment]
This is actually a backend issue for minds/engine
