### ISSUE TITLE
How to running realtime for development

### ISSUE THREAD

**Issue by eva-thientran** [Minds/front#37]
Hello all,
I have a question about how to running real time when I edits the code, currently I have take look docs at https://www.minds.org/docs/install/preparation.html it only have a option to build for production

```
npm run build
```
I guess have option something like ionic server or ng serve but it did not work, anyone have suggestion for that. Thanks

**Comment by johnsmth217** [comment]
I don't think you can see the result of your modified frontend code in real time. So after modifying your code instead of using "npm run build" command use "gulp build --env=development" and you'll have the output.

**Comment by markharding** [comment]
Checkout https://github.com/Minds/front/blob/master/.drone.yml#L14 for the build commands (this is what production runs on).

Merging to https://github.com/Minds/minds/issues/93 to make our docs more clear.
