### ISSUE TITLE
 Twofactor Login No Longer Working

### ISSUE THREAD

**Issue by Francewhoa** [Minds/front#38]
Hi there :)

If this is not the correct place to report this challenge, could you please redirect me to the correct place?

This is to report that the Twofactor Login is no longer working at https://www.minds.com/login So users with that feature activated are not able to log-in Minds.

**Steps to reproduce**
1. If not already done activate your Twofactor Login with https://www.minds.com
1. Log-out
1. Go to https://www.minds.com
1. Click on "LOGIN" button
1. Using the "Login to Minds" form, enter your username and password. Click on "LOGIN" button.
1. The form reads "Twofactor Login". " We just sent you a text. Enter the code below to authenticate." This screenshot shows this form.
![mind---2fa---challenge---2017-12-04---14 33 45---selection_001---francewhoa](https://user-images.githubusercontent.com/119942/33580106-ce543562-d900-11e7-915a-8f830044009b.jpg)
1. The challenge is that the code is never received. So the users are locked out of Minds and can't log-in. One or two weeks ago the "Twofactor Login" was working fine.

Using 
- Firefox 52.5.0 (64-bit)
- Chromium Version 57.0.2987.98 Built on 8.7 (64-bit)
- Google Chrome Version 62.0.3202.94 (64-bit)
- Linux Debian 8.9 at 64 bits
- Mobile phone number in Canada

I first tried to report this challenge at https://www.minds.com/groups/profile/100000000000000681/activity;ts=1512427331951
But I can't because the Twofactor Login is not working. So I'm locked out and can't use Minds.com

I would be happy to contribute testing

My Minds profile at https://www.minds.com/francewhoa

Cheers,

Francewhoa

**Comment by markharding** [comment]
Can you try now?

**Comment by Francewhoa** [comment]
Done. Confirming it works now. I received the SMS with the code. 

Thanks Mark :)

I'm closing this ticket
