### ISSUE TITLE
forgot password not sending e-mail to gmx.com domain

### ISSUE THREAD

**Issue by galenthurber** [Minds/front#39]
I confirmed with GMX that they are not blocking Minds.com
Confirmed this issue by creating a temporary Minds account with a GMX address;
then proceeding to follow forget password procedure. No e-mail arrives; waited over 48 hours.

**Comment by markharding** [comment]
Please contact your email provider. This is not an issue with Minds.com.

**Comment by galenthurber** [comment]
Please provide evidence of e-mail bounces.

**Comment by markharding** [comment]
The issue here lies with your 'gmx' email provider and not Minds.com. Please get in touch with them regarding your mailboxes.

**Comment by galenthurber** [comment]
Has minds blacklisted gmx.com domain?
GMX is not blocking, minds.com is whitelisted.
Will this issue be deleted like 40 was?
"no process to change subscribed e-mail address if domain becomes blacklisted or unreliable"

**Comment by markharding** [comment]
No. Again, please contact your 'gmx' email provider.

**Comment by galenthurber** [comment]
I have contacted them, they are not blocking.
https://en.wikipedia.org/wiki/Whitelist
Are you willing to use a mediator?

**Comment by markharding** [comment]
Apologies, it does appear that gmx.com has been blacklisted for persistent spam abuse. Please email me (mark@minds.com) with an alternative email address so I can resolve your account.

**Comment by galenthurber** [comment]
Thank you, I will

**Comment by galenthurber** [comment]
Thank you, the e-mail change did the trick.
I now can get back to reporting doxxers.
