### ISSUE TITLE
Reminded blogs on channel referring wrong URL 

### ISSUE THREAD

**Issue by bortloff** [Minds/front#4]
Heya guys,

Not sure if this belongs in the front repo, but I'm putting it here, since I can't seem to figure out where it actually goes.

Reproducible: Go to a channel. Find a reminded blog. Hover over, you'll see it'll go to minds.com/view/$guid. Try going to it, it goes to a blank page. Substitute view for blog/view in the URL bar, and you get the blog. The example I'm using is Knightstarr's channel, https://www.minds.com/Knightstarr .

I'd go fix this myself, but without having debugging tools and rifling through the code, I can't seem to figure out where to fix this issue.

**Comment by edgebal** [comment]
Thank you! It looks like there's an issue with blog permalinks from early 2015 and before.
