### ISSUE TITLE
Task 'test' is not in your gulpfile

### ISSUE THREAD

**Issue by gtcode** [Minds/front#43]
Per this doc:

Doing this command: `minds/front $ gulp test`

Getting this result:
```
[19:17:09] Requiring external module ts-node/register
[19:17:11] Using gulpfile ~/projects/github/gtcode/minds/minds/front/gulpfile.ts
[19:17:11] Task 'test' is not in your gulpfile
[19:17:11] Please check the documentation for proper gulpfile formatting
```

**Comment by noiseunit** [comment]
Related to this, I was reading up on gulp.tasks for running tests but it seems Minds perhaps maintains private repos in addition to these public repos from which releases are tested and deployed so I don't want to go down a rabbit hole and look further into making these tests run if they are knowingly running "internal" repos and just not built out here in the public repos. 

Not knowing what the wizards are doing behind the curtains makes it less tempting to spend time on contributing if stuff works in the real source of truth repositories.

**Comment by markharding** [comment]
To execute tests, run `npm test`. Not sure if the docs need updating?
