### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by lapo-luchini** [Minds/front#45]
Yesterday, I created my account with associated SMS auth.
This morning, I correctly authenticated from a different PC.
This afternoon, same PC, I needed to login again (strange), but it isn't working.
On the console I receive a `401` on `https://www.minds.com/api/v1/twofactor/authenticate` and the GUI gets back to the login page with an added red rectangle (which I guess should contain an error, but doesn't):

![image](https://user-images.githubusercontent.com/420454/38991543-6685f9e0-43de-11e8-926d-0017211c4f79.png)

In addition to that, when I try "recover password", my username doesn't exist (and certainly does, it sends me the SMS on login attempt):

![image](https://user-images.githubusercontent.com/420454/38991648-b2455006-43de-11e8-9540-a6f175d9341b.png)

**Comment by lapo-luchini** [comment]
After login/password:
`api/v1/authenticate`: `{status: "error", code: "403", message: "dcd7b11…d333d"}`
then after SMS:
`api/v1/twofactor/authenticate`: `{status: "error", message: "Could not verify."}`

**Comment by eiennohi** [comment]
That exception is thrown when the code verification fails. Maybe you didn't input it correctly?
I've just tested with one of my accounts and 2FA worked ok.

**Comment by ottman** [comment]
That's it. Need to fix that error message. Blank red screen

**Comment by lapo-luchini** [comment]
OK… I have more data, and something funny is happening.
I registred on computer A, I used 2FA, worked at first try.
Then yesterday afternoon I was on computer B, tried 2FA login like 5 or 6 times to no avail… I think I can exclude writing the PIN wrong (for at least some of the tries).
Yesterday evening I was back on computer A and 2FA worked at first try.
Today, back on computer B, it is not working, again (I double checked the number is correct in the HTTP POST).
`{status: "error", message: "Could not verify."}`
So I guess it is somehow dependent on the computer I'm using… either cookie/localStorage data (?), or something else.
BTW: computer A is Chrome/Windows, computer B is Chrome/FreeBSD (and I also tried using Firefox/FreeBSD, to no avail, that's why I'm thinking more about lack of local state had during registration than a software difference).

**Comment by lapo-luchini** [comment]
I can confirm the UI glitch is solved:
![image](https://user-images.githubusercontent.com/420454/39189072-ab43d632-47d1-11e8-9075-c59316b05d1d.png)
…but the underlying problem isn't: I still can't login.
Might the fact that this is not the browser I initially registered from have anything to do with that?

**Comment by lapo-luchini** [comment]
It wa definitely something among my cookies / `localStorage`, as with a "incognito" window it does work and, after having cleared local storage, in a normal window does too.
