### ISSUE TITLE
Infinite 0.002 ETH donation

### ISSUE THREAD

**Issue by Klem** [Minds/front#47]
Hi there.

I noticed that it is possible to loop indefinetly end thus indefinetly receive the 0.002 ETH donation.
I report it as a bug because my understanding of it was that it occured only when you setup your onChain adress for the first time
-Login to metamask
![init](https://user-images.githubusercontent.com/688235/41089135-6379719e-6a41-11e8-9264-013d16cd1379.png)
-Click 'use metamask'
result is :
![result 2](https://user-images.githubusercontent.com/688235/41089558-6dab7652-6a42-11e8-9270-b7a95165819e.png)
-Click 'change' under the eth adress
-Click 'use metamask'
Result is
![result 3](https://user-images.githubusercontent.com/688235/41089590-81567030-6a42-11e8-88b7-492df8af4f42.png)
- And so on....

You get 0.002 ether every time you do that (note the timestamp in the notification), the adress never change and the transactions are validated
![tx](https://user-images.githubusercontent.com/688235/41089643-a03c564a-6a42-11e8-9eb3-30d571f203b8.png)

Hope this is relevant and helpful

**Comment by ottman** [comment]
This is fixed. Would love your feedback on the new app as it's been a while since this issue was created!
