### ISSUE TITLE
Misaligned text in top bar search box

### ISSUE THREAD

**Issue by disciple-dev** [Minds/front#48]
As shown in the image below.

![screenshot](https://user-images.githubusercontent.com/8866130/41262159-292cd5e6-6dd7-11e8-90c0-5ed98f9d21fa.png)

I'm not seeing any console errors. 

Works fine in Firefox, only seeing the problem in Safari Version 11.1 (13605.1.33.1.4) on macOS 10.13.4.

**Comment by ottman** [comment]
This is fixed. Would love your feedback on the new app as it's been a while since this issue was created!
