### ISSUE TITLE
Spelling mistake in FAQ: "Who does a vote do?"

### ISSUE THREAD

**Issue by disciple-dev** [Minds/front#49]
![screen shot 2018-06-12 at 12 43 00 am](https://user-images.githubusercontent.com/8866130/41262621-c9cd05dc-6dd9-11e8-870a-6bccf3b5baff.png)

I guess it comes from here: https://github.com/Minds/front/blob/master/src/app/modules/faq/faq.csv#L77

**Comment by ottman** [comment]
This is fixed. Would love your feedback on the new app as it's been a while since this issue was created!
