### ISSUE TITLE
Selling and exchanging tokens

### ISSUE THREAD

**Issue by ghost** [Minds/front#54]
I think users need to know more about selling and exchanging minds tokens. Currently the [FAQ](https://github.com/Minds/front/blob/master/src/app/modules/faq/faq.csv) and whitepaper, etc say nothing about it.

Users are going to be wondering things like:

- Why can I only withdraw the amount in my OffChain address but not my OnChain address?
- I bought minds tokens, why do they show on minds but not on metamask?
- How do I exchange my minds tokens back to ETH again?

**Comment by ottman** [comment]
This is all handled via Uniswap now. Would love your feedback on the new app as it's been a while since this issue was created!
