### ISSUE TITLE
Pause button for the boosted articles display

### ISSUE THREAD

**Issue by fernandofreamunde** [Minds/front#60]
on top of the feed we have boosted articles rotating, some times there are videos or long text it would be nice to pause the rotation so that we can finish reading/watching.

Also make the total height of that div fixed so that if it is an article with a lot of text it does not push the rest of the feed up and down as it rotates

Thanks :)

**Comment by ottman** [comment]
The Boost rotator has been removed. Would love your feedback on the new app as it's been a while since this issue was created!
